website/music/urls.py
from django.conf.urls import url
from . import views
app_name='music'

urlpatterns=[
    url(r'^$',views.index , name='index'),
    url(r'^(?P<album_id>[0-9]+)/$',views.detail , name='detail'),
    url(r'^(?P<album_id>[0-9]+)/favorite$',views.favorite , name='favorite'),
]

website/python_projectx/urls.py

from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

website/music/models.py
from django.db import models

class Album(models.Model):
    artist=models.CharField(max_length=100)
    title=models.CharField(max_length=100)
    genre=models.CharField(max_length=100)
    album_logo=models.CharField(max_length=250)

    def __str__(self):
       return self.title + ' - ' + self.artist

class Song(models.Model):
    album=models.ForeignKey(Album, on_delete= models.CASCADE)
    file_type=models.CharField(max_length=20)
    song_title=models.CharField(max_length=100)
    is_fav=models.BooleanField(default=False)

    def __str__(self):
       return self.song_title

website/music/views.py

from django.shortcuts import render,get_object_or_404
from .models import Album


def index(request):
    all_albums=Album.objects.all()
    return render(request,'music/index.html', {'all_albums':all_albums})

def detail(request , album_id):
    album=get_object_or_404(Album,pk=album_id)
    return render(request,'music/detail.html', {'album':album})

def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song=album.song_set.get(pk=request.POST['song'])
    except(KeyError, Song.DoesNotExist):
        return render(request,'music/detail.html',
                                     {'album':album,'error_message': "YOU DIDN'T SELECT A SONG"})
    else :
        selected_song.is_fav= True
        selected_song.save()
        return render(request,'music/detail.html',{'album':album})





# Create your views here.


website/music/templates/music/detail.html
<img src="{{album.album_logo}}">

<h1>{{ album.artist}}</h1>
<h2><strong>{{ album.title }}</strong></h2>


<form action="{% url 'music:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
       <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}"  />
       <label for="song{{ forloop.counter }}">
           {{ song.song_title}}
           {% if song.is_fav %}
           <img src="http://www.clker.com/cliparts/L/k/y/e/Y/U/yellow-star-hi.png" >
           {% endif %}
       </label><br>
    {% endfor %}
    <input type="submit" value="Favorite">
</form>

website/music/templates/music/index.html
{% load staticfiles %}
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<!----<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />-->
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'music:index' %}">
                 viber
            </a>
        </div>
    </div>
</nav>

{% if all_albums %}
  <h1>These are all albums</h1>
  <ul>
      {% for album in all_albums %}
         <li><a href="{% url 'music:detail' album.id %}" >{{ album.title }}</a></li>
      {% endfor %}
  </ul>
{% else %}
  <h3>You have nothing</h3>
{% endif %}